name: Java CI

on:
  push:
    paths:
      - main
  pull_request:
    paths:
      - main
  workflow_dispatch:
jobs:
  build-project-a:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build project-a
        run: mvn -B clean package --file project-a/pom.xml

  build-project-b:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build project-b
        run: mvn -B clean package --file project-b/pom.xml

  build-project-c:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build project-c
        run: mvn -B clean package --file project-c/pom.xml


